// <auto-generated />
namespace Pub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class newcontext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newcontext));
        
        string IMigrationMetadata.Id
        {
            get { return "201506211448506_new-context"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
