// <auto-generated />
namespace Pub.Migrations.PubMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class initialMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialMig));
        
        string IMigrationMetadata.Id
        {
            get { return "201506211525228_initialMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
